### ISSUE TITLE
Any network can be added?

### ISSUE THREAD

**Issue by mariocastrogama** [OpenWaterAnalytics/epanet-example-networks#1]
Is this part of the repository intended for WQ problems or any kind of network?

**Comment by samhatchett** [comment]
i really just got this repo started to act as an easy source for networks for doing automated testing of the epanet engine. I think we could use it for many other purposes, right?

feel free to contribute anything you know to be unencumbered by legal restrictions, or otherwise freely available. these first few networks were part of the MSX example network package.
